# ~/.config/starship.toml

# Configure the format of the prompt.
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$git_metrics\
$fill\
$nodejs\
$elixir\
$elm\
$python\
$rust\
$julia\
$c\
$cmd_duration $jobs $time\
$line_break\
$character"""

# format = """
# $username\
# $hostname\
# $directory\
# $git_branch\
# $git_commit\
# $git_state\
# $git_status\
# $git_metrics\
# $fill\
# $cmd_duration $jobs $time\
# $line_break\
# $character"""

# Timeout for commands executed by starship (in milliseconds).
command_timeout = 2000

# Disable the blank line at the start of the prompt
add_newline = true


[fill]
symbol = " "

[directory]
read_only = " "
truncation_length = 3
truncate_to_repo = false
truncation_symbol = "…/"

[git_branch]
symbol = " "
style = 'bold purple'
format = '[$symbol$branch]($style) '

[jobs]
symbol = ""
style = "bold red"
number_threshold = 1
format = '[$symbol]($style)'

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
disabled = false

[git_state]
# style = "bright-black"
format = '\([$state( $progress_current/$progress_total)]($style)\) '

[git_metrics]
disabled = false

[cmd_duration]
style = 'yellow'
format = '[$duration]($style)'

[memory_usage]
symbol = " "

[time]
disabled = false
style = "bold white"
format = "[$time]($style)"

[custom.stunnel]
when = "ps aux | grep stunnel | grep -v grep"
command = "ps -o etime= -p $(ps aux | grep stunnel | grep -v grep | awk '{print $2}')"
style = "red"
format = "[TUNNEL OPEN for $output]($style)"

[rust]
symbol = " "
format = '[$symbol($version )]($style)'

[python]
symbol = " "
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[nodejs]
symbol = " "
format = '[$symbol($version )]($style)'

[julia]
symbol = " "
format = '[$symbol($version )]($style)'

[lua]
symbol = " "
format = '[$symbol($version )]($style)'

[docker_context]
symbol = " "
format = '[$symbol($context )]($style) '

[elixir]
symbol = " "
format = '[$symbol($version \(OTP $otp_version\) )]($style)'

[elm]
symbol = " "
format = '[$symbol($version )]($style)'

[c]
symbol = " "
format = '[$symbol($version )]($style)'
