# [".config/zsh/plugins/powerlevel10k"]
# type = "git-repo"
# url = "https://github.com/romkatv/powerlevel10k.git"
# clone.args = ["--depth", "1"]
# refreshPeriod = "168h"
# [".config/zsh/plugins/zsh-autocomplete"]
# type = "git-repo"
# url = "https://github.com/marlonrichert/zsh-autocomplete.git"
# clone.args = ["--depth", "1"]
# refreshPeriod = "168h"
# [".config/zsh/plugins/zsh-autosuggestions"]
# type = "git-repo"
# url = "https://github.com/zsh-users/zsh-autosuggestions.git"
# refreshPeriod = "168h"
# [".config/zsh/plugins/zsh-completions"]
# type = "git-repo"
# url = "https://github.com/zsh-users/zsh-completions.git"
# refreshPeriod = "168h"
# [".local/share/zsh/site-functions/_yarn"]
# type = "file"
# url = "https://github.com/zsh-users/zsh-completions/blob/master/src/_yarn"
# refreshPeriod = "720h"
# [".local/share/zsh/site-functions/_node"]
# type = "file"
# url = "https://github.com/zsh-users/zsh-completions/blob/master/src/_node"
# refreshPeriod = "720h"
# [".local/share/zsh/site-functions/_direnv"]
# type = "file"
# url = "https://github.com/zsh-users/zsh-completions/blob/master/src/_direnv"
# refreshPeriod = "720h"
# [".local/share/zsh/site-functions/_golang"]
# type = "file"
# url = "https://github.com/zsh-users/zsh-completions/blob/master/src/_golang"
# refreshPeriod = "720h"
# [".local/share/zsh/site-functions/_mix"]
# type = "file"
# url = "https://github.com/zsh-users/zsh-completions/blob/master/src/_mix"
# refreshPeriod = "720h"
# [".config/zsh/plugins/zsh-syntax-highlighting"]
# type = "git-repo"
# url = "https://github.com/zsh-users/zsh-syntax-highlighting.git"
# refreshPeriod = "168h"
