[".config/zsh/plugins/powerlevel10k"]
type = "git-repo"
url = "https://github.com/romkatv/powerlevel10k.git"
exact = true
stripComponents = 1
clone.args = ["--depth", "1"]
refreshPeriod = "168h"
[".config/zsh/plugins/zsh-autocomplete"]
type = "git-repo"
url = "https://github.com/marlonrichert/zsh-autocomplete.git"
exact = true
stripComponents = 1
clone.args = ["--depth", "1"]
refreshPeriod = "168h"
[".config/zsh/plugins/zsh-autosuggestions"]
type = "git-repo"
url = "https://github.com/zsh-users/zsh-autosuggestions.git"
exact = true
stripComponents = 1
refreshPeriod = "168h"
[".config/zsh/plugins/zsh-completions"]
type = "git-repo"
url = "https://github.com/zsh-users/zsh-completions.git"
exact = true
stripComponents = 1
refreshPeriod = "168h"
[".config/zsh/plugins/zsh-syntax-highlighting"]
type = "git-repo"
url = "https://github.com/zsh-users/zsh-syntax-highlighting.git"
exact = true
stripComponents = 1
refreshPeriod = "168h"
