#:schema ./schema/mise.json
#dotenv = '.env'
# [env]

[tools]
# global tool versions go here
# you can set these with `mise use -g`
python = ["3.12", "latest"]
# golang = "latest"
erlang = "latest"
elixir = "latest"
ruby = "latest"
elm = "latest"
# zig = "latest"
# zigmod = "latest"
nim = "latest"
node = "lts"
# bun = "latest"
deno = "latest"
# opam = "latest"
usage = "latest"
neovim = "nightly"
java = "temurin-21"
