#:schema ./schema/rtx.json
#dotenv = '.env'
[env]


[tools]
nodejs = 'lts'
golang = { version = "latest" }
python = { version = "latest" }
erlang = { version = "25.3" }
java = { version = "temurin-17.0.6+10" }
elixir = { version = "1.14.4-otp-25" }
ruby = { version = "latest" }
elm = { version = "latest" }
nim = { version = "latest" }
zig = { version = "latest" }
# direnv = { version = "latest" }

[plugins]
# specify a custom repo url
# note this will only be used if the plugin does not already exist
python = 'https://github.com/jdxcode/rtx-python'
nodejs = 'https://github.com/jdxcode/rtx-nodejs'

[settings] # project-local settings
verbose = true
missing_runtime_behavior = 'warn'
shims_dir = '~/.local/share/rtx/shims'
