#!/usr/bin/env zsh
#### zprof - utility for profiling zsh
# zmodload zsh/zprof # comment out after profiling

# Zsh runs .zshrc for each interactive shell, after .zprofile

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.config/zsh/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

[ -f "${XDG_DATA_HOME:-$HOME/.local/share}/zap/zap.zsh" ] && source "${XDG_DATA_HOME:-$HOME/.local/share}/zap/zap.zsh"

# PLUGINS
plug "romkatv/powerlevel10k"
plug "zsh-users/zsh-completions"
# plug "zap-zsh/supercharge"
plug "zap-zsh/fzf"
# plug "Aloxaf/fzf-tab"
plug "zsh-users/zsh-autosuggestions"
plug "zap-zsh/exa"
plug "zsh-users/zsh-syntax-highlighting"
plug "zsh-users/zsh-history-substring-search"

# LOCAL SCRIPTS
plug "$ZDOTDIR/.config/zsh/exports.zsh"
plug "$ZDOTDIR/.config/zsh/aliases.zsh"
plug "$ZDOTDIR/.config/zsh/functions.zsh"
plug "$ZDOTDIR/.config/zsh/history.zsh"
plug "$ZDOTDIR/.config/zsh/completion.zsh" # Load and initialise completion system

# FZF
# [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh # already covered by plug "zap-zsh/fzf"

# LS_COLORS
if (( $+commands[vivid] )); then
  export LS_COLORS=$(vivid generate catppuccin-mocha)
fi

# replacement for cd command
if (( $+commands[zoxide] )); then
    eval "$(zoxide init zsh)"
fi

# PNPM BUN
# +-----+
path=(
  $XDG_DATA_HOME/pnpm(N)
  $path
)

# ADDITIONAL PATHS - Path's here need to be at the top
path=(
  $HOME/.bin(N)
  $HOME/.local/bin(N)
  $path
)

# KEY BINDINGS
plug "$ZDOTDIR/.config/zsh/keybindings.zsh"

# PROMPT
# To customize prompt, run `p10k configure` or edit ~/.config/zsh/.p10k.zsh.
[[ ! -f ~/.config/zsh/.p10k.zsh ]] || source ~/.config/zsh/.p10k.zsh

# Fabric
if [ -f "~/.config/fabric/fabric-bootstrap.inc" ]; then . "~/.config/fabric/fabric-bootstrap.inc"; fi

# zprof # comment out after profiling #
##### Nothing below this line #######
