#!/bin/zsh

# -U ensures each entry in these is Unique (that is, discards duplicates).
export -U PATH path FPATH fpath MANPATH manpath
export -UT INFOPATH infopath  # -T creates a "tied" pair; see below.

# Shellenv
if (( $+commands[brew] )); then
    eval "$(brew shellenv)"
fi

# $PATH and $path (and also $FPATH and $fpath, etc.) are "tied" to each other.
# Modifying one will also modify the other.
# Note that each value in an array is expanded separately. Thus, we can use ~
# for $HOME in each $path entry.

path=(
    $HOME/.nimble/bin(N) # Nim
    $HOME/.cargo/bin(N) # Rust
    # $HOME/.local/share/solana/install/active_release/bin(N) # Solana
    $HOME/go/bin(N) # Golang
    /Applications/Sublime\ Text.app/Contents/SharedSupport/bin(N) # Sublime Text
    /Applications/Postgres.app/Contents/Versions/latest/bin(N) # Postgress app
    $HOME/Library/Android/sdk/{emulator,platform-tools,tools}(N)
    $HOMEBREW_PREFIX/opt/{mariadb@10.3,ncurses,tomcat@9}/bin(N)
    $HOMEBREW_PREFIX/opt/{coreutils/libexec/gnubin,findutils/libexec/gnubin,grep/libexec/gnubin}/bin(N)
    $HOMEBREW_PREFIX/opt/{curl,gettext,sqlite,llvm}/bin(N)
    # /home/linuxbrew/.linuxbrew/bin(N)
    $path
)

# +-----+
# | FZF |
# +-----+
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# +-------------------+
# | Haskell ghcup-env |
# +-------------------+
[ -f ~/.ghcup/env ] && source ~/.ghcup/env

# +-------------------+
# | Ocaml |
# +-------------------+
[[ ! -r ~/.opam/opam-init/init.zsh ]] || source ~/.opam/opam-init/init.zsh  > /dev/null 2> /dev/null

# +-----+
# | PNPM |
# +-----+
path=(
    $XDG_DATA_HOME/pnpm(N)
    $path
)

################################################################################
## This should come after PATH has been set unless you know what you're doing ##
################################################################################
# # Asdf config
# export ASDF_CONFIG_FILE=$XDG_CONFIG_HOME/asdf/.asdfrc

# if (( $+commands[asdf] )); then
#     # Manage multiple runtime versions with a single CLI tool
#     # . $HOME/.asdf/asdf.sh # This option for when asdf is installed via git
#     . $(brew --prefix)/opt/asdf/libexec/asdf.sh # This option for when asdf is installed via homebrew
# fi

# +--------------------------------------------------+
# | RTX - currently has issues with sublime text path|
# +--------------------------------------------------+
if (( $+commands[rtx] )); then
    export RTX_USE_TOML=1
    export RTX_DATA_DIR=$XDG_DATA_HOME/rtx
    # export RTX_ASDF_COMPAT=1
    
    eval "$(rtx activate zsh)"
    eval "$(rtx hook-env)"  # enable this if not using rtx shims
fi

################################################################################

# +-----------------------------------------------------+
# | I need $HOME/.local/bin to be at head of path hence |
# +----------------------------------------------------+
path=(
    # $HOME/.bin(N)
    # $HOME/.local/share/rtx/shims(N)
    $HOME/.local/bin(N)
    $path
)