[[language]]
name = "python"
auto-format = true
diagnostic-severity = "Hint"
formatter = { command = "black", args = ["--quiet", "-"] }

[[language]]
name = "elixir"
auto-format = true
scope = "source.elixir"
injection-regex = "(elixir)"
file-types = ["ex", "exs", "heex", "eex", "mix.lock"]
shebangs = ["elixir"]
roots = ["mix.exs"]
comment-token = "#"
diagnostic-severity = "Hint"
language-server = { command = "elixir-ls" }
config = { elixirLS.dialyzerEnabled = true }
indent = { tab-width = 2, unit = " " }

[[language]]
name = "rust"
auto-format = true
diagnostic-severity = "Hint"

[language.config]
checkOnSave = { command = "clippy" }

[[language]]
name = "elm"
auto-format = true
diagnostic-severity = "Hint"

[[language]]
name = "julia"
auto-format = true
diagnostic-severity = "Hint"

[[language]]
name = "javascript"
auto-format = true
diagnostic-severity = "Hint"

[[language]]
name = "haskell"
auto-format = true
diagnostic-severity = "Hint"

[[language]]
name = "ocaml"
auto-format = true
diagnostic-severity = "Hint"

[[language]]
name = "lua"
auto-format = true
diagnostic-severity = "Hint"

[[language]]
name = "html"
auto-format = true
diagnostic-severity = "Hint"
